services:
  pgdb:
    image: postgres:16.5-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin4.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 4000
    volumes:
      - ./.pgadmin:/var/lib/pgadmin
    ports:
      - 4000:4000

  redis-node-1:
    image: redis:7.4-alpine
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "no" ]
    ports:
      - 6379:6379

  redis-node-2:
    image: redis:7.4-alpine
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "no" ]
    ports:
      - 16379:6379

  redis-node-3:
    image: redis:7.4-alpine
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "no" ]
    ports:
      - 26379:6379

  redis-node-4:
    image: redis:7.4-alpine
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "no" ]
    ports:
      - 36379:6379

  redis-node-5:
    image: redis:7.4-alpine
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "no" ]
    ports:
      - 46379:6379

  redis-node-6:
    image: redis:7.4-alpine
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "no" ]
    ports:
      - 56379:6379

  redis-cluster-creator:
    image: redis:7.4-alpine
    command: redis-cli --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6